package com.algomentor.backend;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.LinkedHashMap;
import java.util.Map;

@RestController
@Tag(name = "System", description = "Service status")
public class HealthController {

    private final LlmConfig llmConfig;

    public HealthController(LlmConfig llmConfig) {
        this.llmConfig = llmConfig;
    }

    @GetMapping("/api/health")
    @Operation(
            summary = "Service health and active mode",
            description = "Reports whether the service is up and whether analyses are backed by a "
                    + "real model ('live') or generated offline ('demo')."
    )
    public Map<String, Object> health() {
        boolean demo = llmConfig.demoMode();

        Map<String, Object> body = new LinkedHashMap<>();
        body.put("ok", true);
        body.put("mode", demo ? "demo" : "live");
        body.put("model", demo ? null : llmConfig.model());
        body.put("message", demo
                ? "Demo mode: analyses are generated offline. Set OPENAI_API_KEY in .env.local for real analysis."
                : "Live mode: analyses are generated by the configured model.");
        return body;
    }
}
